-- AIR-93: Fijar search_path en 34 funciones (patrón mig-007: public, pg_catalog). Cierra advisor function_search_path_mutable.

ALTER FUNCTION public.update_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.set_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.fn_snapshot_cogs_en_venta_item() SET search_path = public, pg_catalog;
ALTER FUNCTION public.fn_webhook_e2_huerfanos_log_updated_at() SET search_path = public, pg_catalog;
ALTER FUNCTION public.fn_propagar_cogs_a_variantes() SET search_path = public, pg_catalog;
ALTER FUNCTION public.validar_nombre_adset_consistente() SET search_path = public, pg_catalog;
ALTER FUNCTION public.validar_nombre_campaign_consistente() SET search_path = public, pg_catalog;
ALTER FUNCTION public.sync_ubicaciones(locations_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.backfill_inventario(inventory_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.backfill_products(products_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.backfill_single_order(order_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_inventory_level(level_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_shopify_journey(journeys_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_meta_ads(ads_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_klaviyo_campaigns(campaigns_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_meta_organic(posts_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_amplitude_daily(metrics_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_amplitude_top_content(content_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_klaviyo_profiles(profiles_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.upsert_customer(customer_data jsonb) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_orders_pending_journey() SET search_path = public, pg_catalog;
ALTER FUNCTION public.extract_utm_param(url text, param_name text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.es_tarjeta_regalo(p_producto_id uuid) SET search_path = public, pg_catalog;
ALTER FUNCTION public.is_color_value(val text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.inferir_color_desde_titulo(titulo text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_mix_producto(p_desde date, p_hasta date, p_canal text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_clientes_segmentacion() SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_memoria_activa(dominio_filtro text, limite_insights integer, limite_learnings integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.buscar_creativos(query_embedding vector, limite integer, filtro_objetivo text, filtro_audiencia text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.buscar_productos(query_embedding vector, limite integer, filtro_coleccion text, filtro_tipo text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.buscar_brand_knowledge(query_embedding vector, limite integer, filtro_categoria text) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_performance_snapshot(p_canal text, p_desde date, p_hasta date) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_meta_ads_diagnostico(p_dias integer) SET search_path = public, pg_catalog;
ALTER FUNCTION public.get_estado_sistema() SET search_path = public, pg_catalog;

-- ROLLBACK (ejecutar en orden inverso si fuera necesario deshacer):
-- ALTER FUNCTION public.get_estado_sistema() RESET search_path;
-- ALTER FUNCTION public.get_meta_ads_diagnostico(p_dias integer) RESET search_path;
-- ALTER FUNCTION public.get_performance_snapshot(p_canal text, p_desde date, p_hasta date) RESET search_path;
-- ALTER FUNCTION public.buscar_brand_knowledge(query_embedding vector, limite integer, filtro_categoria text) RESET search_path;
-- ALTER FUNCTION public.buscar_productos(query_embedding vector, limite integer, filtro_coleccion text, filtro_tipo text) RESET search_path;
-- ALTER FUNCTION public.buscar_creativos(query_embedding vector, limite integer, filtro_objetivo text, filtro_audiencia text) RESET search_path;
-- ALTER FUNCTION public.get_memoria_activa(dominio_filtro text, limite_insights integer, limite_learnings integer) RESET search_path;
-- ALTER FUNCTION public.get_clientes_segmentacion() RESET search_path;
-- ALTER FUNCTION public.get_mix_producto(p_desde date, p_hasta date, p_canal text) RESET search_path;
-- ALTER FUNCTION public.inferir_color_desde_titulo(titulo text) RESET search_path;
-- ALTER FUNCTION public.is_color_value(val text) RESET search_path;
-- ALTER FUNCTION public.es_tarjeta_regalo(p_producto_id uuid) RESET search_path;
-- ALTER FUNCTION public.extract_utm_param(url text, param_name text) RESET search_path;
-- ALTER FUNCTION public.get_orders_pending_journey() RESET search_path;
-- ALTER FUNCTION public.upsert_customer(customer_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_klaviyo_profiles(profiles_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_amplitude_top_content(content_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_amplitude_daily(metrics_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_meta_organic(posts_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_klaviyo_campaigns(campaigns_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_meta_ads(ads_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_shopify_journey(journeys_data jsonb) RESET search_path;
-- ALTER FUNCTION public.upsert_inventory_level(level_data jsonb) RESET search_path;
-- ALTER FUNCTION public.backfill_single_order(order_data jsonb) RESET search_path;
-- ALTER FUNCTION public.backfill_products(products_data jsonb) RESET search_path;
-- ALTER FUNCTION public.backfill_inventario(inventory_data jsonb) RESET search_path;
-- ALTER FUNCTION public.sync_ubicaciones(locations_data jsonb) RESET search_path;
-- ALTER FUNCTION public.validar_nombre_campaign_consistente() RESET search_path;
-- ALTER FUNCTION public.validar_nombre_adset_consistente() RESET search_path;
-- ALTER FUNCTION public.fn_propagar_cogs_a_variantes() RESET search_path;
-- ALTER FUNCTION public.fn_webhook_e2_huerfanos_log_updated_at() RESET search_path;
-- ALTER FUNCTION public.fn_snapshot_cogs_en_venta_item() RESET search_path;
-- ALTER FUNCTION public.set_updated_at() RESET search_path;
-- ALTER FUNCTION public.update_updated_at() RESET search_path;
