-- RESPALDO RECONSTRUIDO del estado vivo en PROD (AIR-162). NO es el SQL original de la migración '056_cola_agrupada_insight_key' (aplicada 20260607213521). Ya vivo en PROD; este archivo es respaldo fiel git (AIR-90). Idempotente.

CREATE OR REPLACE VIEW analytics.view_dashboard_cola_agrupada AS
 WITH base AS (
         SELECT insights.id,
            insights.dominio,
            insights.tipo,
            insights.titulo,
            insights.descripcion,
            insights.metrica_clave,
            insights.valor_observado,
            insights.valor_referencia,
            insights.delta_pct,
            insights.score_confianza,
            insights.vigente,
            insights.veces_confirmado,
            insights.ultima_confirmacion,
            insights.accion_sugerida,
            insights.accion_tomada,
            insights.accion_notas,
            insights.periodo_inicio,
            insights.periodo_fin,
            insights.embedding,
            insights.created_at,
            insights.updated_at,
            insights.accion_evaluada,
            insights.accion_tomada_at,
            insights.accion_tomada_por,
            insights.requiere_del_humano,
            insights.ttl_accion,
            insights.estado_accion,
            insights.snooze_hasta,
            insights.insight_key,
            COALESCE(insights.insight_key, insights.id::text) AS grupo_key
           FROM insights
          WHERE insights.vigente = true AND COALESCE(insights.score_confianza, 0::numeric) > 0.6 AND (insights.requiere_del_humano IS DISTINCT FROM 'nada'::text OR (insights.estado_accion = ANY (ARRAY['hecho'::text, 'descartado'::text, 'pospuesto'::text])))
        ), agg AS (
         SELECT base.grupo_key,
            count(*) AS veces_en_grupo,
            min(COALESCE(base.periodo_inicio, base.created_at::date)) AS primera_aparicion,
            max(COALESCE(base.ultima_confirmacion, base.created_at)) AS ultima_aparicion,
            array_agg(base.id ORDER BY (COALESCE(base.ultima_confirmacion, base.created_at)) DESC, base.created_at DESC) AS ids_grupo
           FROM base
          GROUP BY base.grupo_key
        ), rep AS (
         SELECT DISTINCT ON (base.grupo_key) base.id,
            base.dominio,
            base.tipo,
            base.titulo,
            base.descripcion,
            base.metrica_clave,
            base.valor_observado,
            base.valor_referencia,
            base.delta_pct,
            base.score_confianza,
            base.vigente,
            base.veces_confirmado,
            base.ultima_confirmacion,
            base.accion_sugerida,
            base.accion_tomada,
            base.accion_notas,
            base.periodo_inicio,
            base.periodo_fin,
            base.embedding,
            base.created_at,
            base.updated_at,
            base.accion_evaluada,
            base.accion_tomada_at,
            base.accion_tomada_por,
            base.requiere_del_humano,
            base.ttl_accion,
            base.estado_accion,
            base.snooze_hasta,
            base.insight_key,
            base.grupo_key
           FROM base
          ORDER BY base.grupo_key, (COALESCE(base.ultima_confirmacion, base.created_at)) DESC, base.created_at DESC
        )
 SELECT rep.id,
    rep.dominio,
    rep.tipo,
    rep.titulo,
    rep.descripcion,
    rep.metrica_clave,
    rep.valor_observado,
    rep.valor_referencia,
    rep.delta_pct,
    rep.score_confianza,
    rep.veces_confirmado,
    rep.ultima_confirmacion,
    rep.accion_sugerida,
    rep.accion_tomada,
    rep.periodo_inicio,
    rep.periodo_fin,
    rep.created_at,
    rep.accion_tomada_at,
    rep.accion_tomada_por,
    rep.accion_notas,
    rep.requiere_del_humano,
    rep.ttl_accion,
    rep.estado_accion,
    rep.snooze_hasta,
    rep.insight_key,
    rep.grupo_key,
    agg.veces_en_grupo,
    agg.primera_aparicion,
    agg.ultima_aparicion,
    agg.ids_grupo
   FROM rep
     JOIN agg USING (grupo_key)
  ORDER BY rep.score_confianza DESC NULLS LAST, agg.ultima_aparicion DESC NULLS LAST;
